#
# Arun Krishnakumar Rajagoapalan 623007516
#

CC = clang++     # the c++ compiler to use

default:all

p1:
	clang++ p1.cpp -o p1.o

p2:
	clang++ p2.cpp -o p2.o

p3:
	clang++ p3.cpp -o p3.o

p4:
	clang++ p4.cpp -o p4.o

clean:
	rm *.o