#
# Arun Krishnakumar Rajagoapalan 623007516
#

CC = clang++     # the c++ compiler to use

default:all

p1:
	clang++ p1.cpp -o p1.o -std=c++11

p2:
	clang++ p2.cpp -o p2.o -std=c++11

p3:
	clang++ p3.cpp -o p3.o -std=c++11

p4:
	clang++ p4.cpp -o p4.o -std=c++11

clean:
	rm *.o
